name: amyos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-40/bieszczaders-kernel-cachyos-fedora-40.repo
      - https://raw.githubusercontent.com/ublue-os/bluefin/main/system_files/dx/etc/yum.repos.d/vscode.repo
      - https://copr.fedorainfracloud.org/coprs/karmab/kcli/repo/fedora-40/karmab-kcli-fedora-40.repo
    install:
      - kernel-cachyos
      - ubuntu-family-fonts
      - yaru-theme
      - code
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra
      - kernel-uki-virt

  - type: default-flatpaks
    notify: true
    system:
      install:
      remove:

  - type: signing
