name: amyos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
    install:
      - kernel-cachyos
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra

  - type: default-flatpaks
    notify: true
    system:
      install:
      remove:

  - type: signing
