name: amyos
description: https://blue-build.org/

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/astrovm/amyos/live/repos/vscode.repo
    install:
      - alacritty
      - android-tools
      - aria2
      - binutils
      - binutils-devel
      - code
      - croc
      - diffstat
      - doxygen
      - easyeffects
      - emacs
      - fastfetch
      - firewall-config
      - gcc
      - gcc-c++
      - gettext
      - gparted
      - kdeconnectd
      - kitty
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - lld
      - lm_sensors
      - libxcrypt-compat
      - mpv
      - neofetch
      - neovim
      - net-tools
      - openssl-devel
      - p7zip
      - p7zip-plugins
      - patch
      - patchutils
      - perl-Image-ExifTool
      - python3-pip
      - qemu-kvm
      - subversion
      - systemtap
      - tmux
      - util-linux-user
      - virt-install
      - virt-manager
      - virt-viewer
      - vlc
      - wireguard-tools
      - zsh

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.calibre_ebook.calibre
        - com.github.Matoking.protontricks
        - com.github.k4zmu2a.spacecadetpinball
        - com.github.micahflee.torbrowser-launcher
        - com.stremio.Stremio
        - com.usebottles.bottles
        - com.ylsoftware.qmmp.Qmmp
        - io.github.hakuneko.HakuNeko
        - io.gitlab.librewolf-community
        - it.mijorus.gearlever
        - net.davidotek.pupgui2
        - net.lutris.Lutris
        - net.pcsx2.PCSX2
        - network.loki.Session
        - org.atheme.audacious
        - org.audacityteam.Audacity
        - org.duckstation.DuckStation
        - org.gimp.GIMP
        - org.kde.kdenlive
        - org.qbittorrent.qBittorrent
        - org.signal.Signal
        - org.telegram.desktop
        - org.yuzu_emu.yuzu

  - type: signing
