name: amyos
description: https://blue-build.org/

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - android-tools
      - aria2
      - croc
      - easyeffects
      - gparted
      - mpv
      - neofetch
      - neovim
      - net-tools
      - tmux
      - util-linux-user
      - virt-manager
      - vlc
      - wireguard-tools
      - zsh

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.calibre_ebook.calibre
        - com.github.k4zmu2a.spacecadetpinball
        - com.github.micahflee.torbrowser-launcher
        - com.stremio.Stremio
        - com.usebottles.bottles
        - io.github.hakuneko.HakuNeko
        - io.gitlab.librewolf-community
        - it.mijorus.gearlever
        - net.davidotek.pupgui2
        - net.lutris.Lutris
        - net.pcsx2.PCSX2
        - network.loki.Session
        - org.atheme.audacious
        - org.audacityteam.Audacity
        - org.duckstation.DuckStation
        - org.gimp.GIMP
        - org.kde.kdenlive
        - org.qbittorrent.qBittorrent
        - org.signal.Signal
        - org.telegram.desktop
        - org.yuzu_emu.yuzu

  - type: signing
