name: amyos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
    install:
      - steam
      - lutris
    remove:

  - type: default-flatpaks
    notify: true
    system:
      install:
      remove:

  - type: signing
