# image will be published to ghcr.io/<user>/<name>
name: amy-os
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://raw.githubusercontent.com/astrolince/amy-os/live/repos/vscode.repo
    install:
      # - micro
      # - starship
      - android-tools
      - aria2
      - code
      - emacs
      - exa
      - firewall-config
      - gparted
      - kdeconnectd
      - kitty
      - langpacks-en
      - lm_sensors
      - neofetch
      - neovim
      - net-tools
      - p7zip
      - p7zip-plugins
      - tmux
      - util-linux-user
      - virt-manager
      - wireguard-tools
      - zsh
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita
      - com.bitwarden.desktop
      - com.brave.Browser
      - com.calibre_ebook.calibre
      - com.discordapp.Discord
      - com.github.k4zmu2a.spacecadetpinball
      - com.github.micahflee.torbrowser-launcher
      - com.github.tchx84.Flatseal
      - com.github.wwmm.easyeffects
      - com.microsoft.Edge
      - com.obsproject.Studio
      - com.obsproject.Studio.Plugin.GStreamerVaapi
      - com.obsproject.Studio.Plugin.Gstreamer
      - com.obsproject.Studio.Plugin.OBSVkCapture
      - com.spotify.Client
      - com.stremio.Stremio
      - com.teamspeak.TeamSpeak
      - com.valvesoftware.Steam
      - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
      - com.valvesoftware.Steam.Utility.gamescope
      - com.valvesoftware.Steam.Utility.steamtinkerlaunch
      - de.shorsh.discord-screenaudio
      - im.riot.Riot
      - io.github.celluloid_player.Celluloid
      - io.github.hakuneko.HakuNeko
      - io.gitlab.librewolf-community
      - io.mpv.Mpv
      - net._86box._86Box
      - net.davidotek.pupgui2
      - net.lutris.Lutris
      - net.pcsx2.PCSX2
      - network.loki.Session
      - org.audacityteam.Audacity
      - org.blender.Blender
      - org.duckstation.DuckStation
      - org.fedoraproject.MediaWriter
      - org.freedesktop.Platform.VulkanLayer.MangoHud
      - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
      - org.gimp.GIMP
      - org.gnome.Extensions
      - org.gnome.NautilusPreviewer
      - org.kde.kdenlive
      - org.kde.krita
      - org.libreoffice.LibreOffice
      - org.qbittorrent.qBittorrent
      - org.signal.Signal
      - org.standardnotes.standardnotes
      - org.telegram.desktop
      - org.videolan.VLC
      - org.yuzu_emu.yuzu

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
