# image will be published to ghcr.io/<user>/<name>
name: amy-os
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://raw.githubusercontent.com/astrolince/amy-os/live/repos/vscode.repo
    install:
      # - micro
      # - starship
      - android-tools
      - aria2
      - code
      - emacs
      - exa
      - firewall-config
      - gparted
      - kdeconnectd
      - kitty
      - langpacks-en
      - lm_sensors
      - neofetch
      - neovim
      - net-tools
      - p7zip
      - p7zip-plugins
      - tmux
      - util-linux-user
      - virt-manager
      - wireguard-tools
      - zsh
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita
      - Bitwarden: com.bitwarden.desktop
      - Brave: com.brave.Browser
      - calibre: com.calibre_ebook.calibre
      - Discord: com.discordapp.Discord
      - Space Cadet Pinball: com.github.k4zmu2a.spacecadetpinball
      - Tor Browser: com.github.micahflee.torbrowser-launcher
      - Flatseal: com.github.tchx84.Flatseal
      - Easy Effects: com.github.wwmm.easyeffects
      - Microsoft Edge: com.microsoft.Edge
      - OBS Studio: com.obsproject.Studio
      - OBS GStreamer VA-API Plugin: com.obsproject.Studio.Plugin.GStreamerVaapi
      - OBS GStreamer Plugin: com.obsproject.Studio.Plugin.Gstreamer
      - OBS VkCapture Plugin: com.obsproject.Studio.Plugin.OBSVkCapture
      - Spotify: com.spotify.Client
      - Stremio: com.stremio.Stremio
      - TeamSpeak: com.teamspeak.TeamSpeak
      - Steam: com.valvesoftware.Steam
      - Steam - Proton-GE: com.valvesoftware.Steam.CompatibilityTool.Proton-GE
      - Gamescope: org.freedesktop.Platform.VulkanLayer.gamescope
      - SteamTinkerLaunch: com.valvesoftware.Steam.Utility.steamtinkerlaunch
      - discord-screenaudio: de.shorsh.discord-screenaudio
      - Element: im.riot.Riot
      - Celluloid: io.github.celluloid_player.Celluloid
      - HakuNeko: io.github.hakuneko.HakuNeko
      - LibreWolf: io.gitlab.librewolf-community
      - mpv: io.mpv.Mpv
      - 86Box: net._86box._86Box
      - ProtonUp-Qt: net.davidotek.pupgui2
      - Lutris: net.lutris.Lutris
      - PCSX2: net.pcsx2.PCSX2
      - Session: network.loki.Session
      - Audacity: org.audacityteam.Audacity
      - Blender: org.blender.Blender
      - DuckStation: org.duckstation.DuckStation
      - Fedora Media Writer: org.fedoraproject.MediaWriter
      - MangoHud: org.freedesktop.Platform.VulkanLayer.MangoHud
      - OBS VkCapture tools: org.freedesktop.Platform.VulkanLayer.OBSVkCapture
      - GIMP: org.gimp.GIMP
      - Extensions: org.gnome.Extensions
      - Nautilus - Sushi: org.gnome.NautilusPreviewer
      - Kdenlive: org.kde.kdenlive
      - Krita: org.kde.krita
      - LibreOffice: org.libreoffice.LibreOffice
      - qBittorrent: org.qbittorrent.qBittorrent
      - Signal: org.signal.Signal
      - Standard Notes: org.standardnotes.standardnotes
      - Telegram: org.telegram.desktop
      - VLC: org.videolan.VLC
      - yuzu: org.yuzu_emu.yuzu

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
